-- MySQL Script generated by MySQL Workbench
-- Model: Url Shortener    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema url_shortener
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `url_shortener` DEFAULT CHARACTER SET utf8 ;
USE `url_shortener` ;


-- -----------------------------------------------------
-- Table `url_shortener`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url_shortener`.`user` ;

CREATE TABLE IF NOT EXISTS `url_shortener`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `url_shortener`.`url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url_shortener`.`url` ;

CREATE TABLE IF NOT EXISTS `url_shortener`.`url` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `full_url` TEXT NOT NULL,
  `hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_url_user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  CONSTRAINT `fk_url_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `url_shortener`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `url_shortener`.`url_visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url_shortener`.`url_visit` ;

CREATE TABLE IF NOT EXISTS `url_shortener`.`url_visit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url_id` INT(11) NOT NULL,
  `referer` VARCHAR(45) NOT NULL,
  `visited_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_url_visit_url_id_idx` (`url_id` ASC),
  CONSTRAINT `fk_url_visit_url_id`
    FOREIGN KEY (`url_id`)
    REFERENCES `url_shortener`.`url` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;